### ISSUE TITLE
Link testing

### ISSUE THREAD

**Issue by klequis** [tvc-school-org/tvc-school#2]
Try all links in app other than Hints & Tips (or things that say CSS for ... or JSX for ....)
For example
> TOC
> Footer
> Other?

**Comment by klequis** [comment]
Use production site
http://react-challenge-01.s3-website-us-west-2.amazonaws.com/

**Comment by LauraSilvey** [comment]
1. Added MDN Array.map to link in the Intro section.
2. Fixed typos along the way.
